### PR TITLE
Use TypeScript, Bun, simplified project structure

### PR DESCRIPTION
**Pull request by ctjlewis**
This is such an amazing implementation, but these changes make the code much easier to work with and extend for ANSI.

### CODE REVIEW

**Comment by ctjlewis** [comment]
Fuck. I meant to send this to my own fork.

**Comment by ctjlewis** [comment]
If you'd actually entertain a merge lmk and I'll reopen. But def an accident.

**Comment by thetarnav** [comment]
I chose jsdoc and node for simplicity, on purpose, so I don’t intend to change that yet.
Good luck with your fork though and lmk if you make improvements to the implementation.

**Comment by ctjlewis** [comment]
No, your implementation is perfect. I wasted days trying to do this from scratch, I can just add an ANSI renderer.

If you have any notes on doing that let me know. Will just wrap parsed text with ChalkInstance rather than HTMLElement.

**Comment by thetarnav** [comment]
Ah you are planning to just change the renderer? I thought you were planning on internal improvements, hence the fork and port to typescript.
Since you've moved the code to typescript you should be familiar with how the renderer interface works, you can use the examples of the dom, logger and test renderers to see how you can make your own.
I haven't used chalk, but isn't that only for formatting ansi and not rendering? How are you planning to actually render the text? Just directly writing to stdout?

**Comment by ctjlewis** [comment]
I'm actually gonna use this to write a `TransformStream<Uint8Array, Uint8Array>` for the universal stream case. For now I'm just piping to stdout.

I'm noticing this is a little tricky because we need to adjust the text at `addText()` time, to add padding for headings/paragraphs manually and render checkboxes etc. It will probably need to support prefix and suffix content for ANSI streaming case. But this has to flow through `addText()` to stream in like HTMLRenderer as far as I can tell.

https://github.com/SpellcraftAI/streaming-markdown/blob/37f914b83bd625e9fb4e0c769526f3d426a00b89/src/renderer/ansi.ts#L7-L121

**Comment by ctjlewis** [comment]
I have an initial version working. The renderer will eventually need token metadata, so `Token` will just have an `type` that is the current enum. For instance,  a `Token` with `Token.type: TokenType.CHECKBOX` will have something like `Token.checked: boolean` which tells us whether to render ` [ ] ` or ` [x] `.

This was all handled automatically by the DOM for the HTMLRenderer. Which is a truly beautiful approach by the way. 

image

**Pull request closed without merging**
